<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Validador\**" />
    <EmbeddedResource Remove="Validador\**" />
    <None Remove="Validador\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Validador\DominioValidator.cs" />
    <Compile Include="Validador\PerfilValidator.cs" />
    <Compile Include="Validador\ProductoValidator.cs" />
    <Compile Include="Validador\RolUsuarioValidator.cs" />
    <Compile Include="Validador\RolValidator.cs" />
    <Compile Include="Validador\UsuarioValidator.cs" />
    <Compile Include="Validador\ZonaGeograficaValidator.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Datos\Datos.csproj" />
    <ProjectReference Include="..\Comun\Comun.csproj" />
  </ItemGroup>

</Project>
